name: "docker-build"
description: "docker build"
inputs:
    username:
        required: true
    password:
        required: true
    imagename:
        required: true
    tagname:
        default: "latest"
# outputs:
#     random-number:
#         description: "Random number"
#         value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
    using: "composite"
    steps:
        - name: print
          run: echo "username:${{ inputs.username }}"
        # - name: print
        #   run: echo "username:${OWNER,,}"
        #   env:
        #       OWNER: ${{ inputs.username }}
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${OWNER,,}
              password: ${{ inputs.password }}
          env:
              OWNER: ${{ inputs.username }}
        - run: docker build . --tag ghcr.io/${OWNER,,}/${{ inputs.imagename }}:${{ inputs.tagname }}
          env:
              OWNER: ${{ inputs.username }}
          shell: bash
        - name: Build and push Docker image to GitHub Container Registry
          uses: docker/build-push-action@v3
          with:
              push: true
              tags: |
                  ghcr.io/${{ ${OWNER,,} }}/${{ inputs.imagename }}:${{ inputs.tagname }}
          env:
              OWNER: ${{ inputs.username }}
