name: "docker-build"
description: "docker build"
# inputs:
#     who-to-greet: # id of input
#         description: "Who to greet"
#         required: true
#         default: "World"
# outputs:
#     random-number:
#         description: "Random number"
#         value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
    using: "composite"
    steps:
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${OWNER,,}
              password: ${{ secrets.GHCR_PAT }}
          env:
              OWNER: ${{ github.repository_owner }}
        - run: docker build . --tag ghcr.io/mamedenq/example_image:latest
          shell: bash
        - name: Build and push Docker image to GitHub Container Registry
          uses: docker/build-push-action@v3
          with:
              push: true
              tags: |
                  ghcr.io/${OWNER,,}/example_image:latest
              # labels: |
              #     org.opencontainers.image.source=${{ github.event.repository.clone_url }}
              # cache-from: type=local,src=/tmp/.buildx-cache
              # cache-to: type=local,dest=/tmp/.buildx-cache-new
              # build-args: |
              #     RUBY_VERSION=${{ steps.prepare_build_arg.outputs.RUBY_VERSION }}
              #     BUNDLER_VERSION=${{ steps.prepare_build_arg.outputs.BUNDLER_VERSION }}
          env:
              OWNER: ${{ github.repository_owner }}
