version: "3"
services:
    curl-example-app:
        # build: .
        build:
            context: .docker/
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        tty: true
