name: example-otherfile

# on: workflow_dispatch
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    path:
        - "!Dockerfile"

jobs:
    job-1:
        name: job-1
        runs-on: ubuntu-latest
        steps:
            - name: echo_info
              run: echo "example-otherfile"
