name: example-dockerfile

on:
    push:
        branches: ["master"]
        paths:
            - "!**"
            - "Dockerfile"
    pull_request:
        branches: ["master"]
        paths:
            - "!**"
            - "Dockerfile"

jobs:
    job-1:
        name: job-1
        runs-on: ubuntu-latest
        steps:
            - name: echo_info
              run: echo "example-dockerfile"
