name: example-otherfile

# on: workflow_dispatch
on:
    push:
        branches: ["master"]
        paths-ignore:
            - "Dockerfile"
    pull_request:
        branches: ["master"]
        paths-ignore:
            - "Dockerfile"

jobs:
    job-1:
        name: job-1
        runs-on: ubuntu-latest
        steps:
            - name: echo_info
              run: echo "example-otherfile"
