name: flow-a

on: workflow_dispatch

jobs:
    job_a:
        name: job_a
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "run flow_a"
    job_call_hello:
        # - name: Get changed files
        #   id: changed-files
        #   uses: tj-actions/changed-files@v29.0.2
        # - name: example
        #   if: contains(steps.changed-files.outputs.all_modified_files, "Dockerfile")
        #   uses: actions/hello
        name: job_call_hello
        runs-on: ubuntu-latest
        steps:
            - name: example
              uses: ./github/actions/hello
    job_call_b:
        uses: ./.github/workflows/flow_b.yml
