name: flow-a

on: workflow_dispatch

jobs:
    job_a:
        name: job_a
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "run flow_a"
    job_call_b:
        uses: .github/workflows/flow_b.yml
