name: unit-test

on: workflow_dispatch
# on:
#     push:
#         branches: ["master"]
#     pull_request:
#         branches: ["master"]

jobs:
    job-docker-build:
        name: job-docker-build
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v29.0.2
            - name: docker-build
              if: contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile')
              uses: ./.github/actions/docker_build
              with:
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_PAT }}
    job-unit-test:
        needs: job-docker-build
        name: job-unit-test
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "unit-test"
            # docker pull ghcr.io/n-jun-k2/sample-actions/python:v1
            # - name: docker compose up
            #   run: docker-compose up -d
            # - name: python test
            #   run: docker-compose exec -T app pytest
