name: unit-test

# on: workflow_dispatch
# on: workflow_dispatch
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    job-docker-build:
        name: job-docker-build
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v29.0.2
            - name: docker-build
              if: contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile')
              uses: ./.github/actions/docker_build
              with:
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_PAT }}
                  imagename: "example_container"
                  tagname: "latest"
    job-unit-test:
        needs: job-docker-build
        name: job-unit-test
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${OWNER,,}
                  password: ${{ secrets.GHCR_PAT }}
              env:
                  OWNER: ${{ github.repository_owner }}
            - name: docker compose up
              run: docker-compose up -d
            - name: python test
              run: docker-compose exec -T app pytest
